repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: npm-format-check
        name: npm format check
        entry: npm run format:check
        language: system
        pass_filenames: false
      - id: npm-lint
        name: npm lint
        entry: npm run lint
        language: system
        pass_filenames: false
